[package]
name = "stakehouse"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-compact = { git = "https://github.com/jedisct1/rust-ed25519-compact", branch = "master", features = ["std", "pem"] }


chain = { path = "./lib/chain" }
